### ISSUE TITLE
Update README with badges

### ISSUE THREAD

**Issue by llyram** [Maryll-castelino/Declare#1]
The [built with](https://github.com/Maryll-castelino/Declare#built-with) section of the README has bullet points.
Change that to SVG badges to make it look better

Refer to:
- https://github.com/alexandresanlim/Badges4-README.md-Profile
- https://github.com/Naereen/badges
- https://github.com/badges/shields
- https://shields.io/

**Comment by Kiinitix** [comment]
Hey, can I take this?

**Comment by Misterr-H** [comment]
@Kiinitix hey are u working on it?

**Comment by Kiinitix** [comment]
@Misterr-H Yes. Just waiting for @Maryll-castelino to assign me this issue.

**Comment by llyram** [comment]
I'll assign @Kiinitix to this issue

**Comment by llyram** [comment]
Leave a star⭐ on the repo if you like 😊

**Comment by Kiinitix** [comment]
sure 😀
