### ISSUE TITLE
Add Dicebear avatars

### ISSUE THREAD

**Issue by llyram** [Maryll-castelino/Declare#3]
Add dicebear pixel avatars to player indicator
https://github.com/dicebear/dicebear

<div style="display: flex;">
<img height="100px" src="https://avatars.dicebear.com/api/pixel-art/maryll.svg">
<img height="100px" src="https://avatars.dicebear.com/api/pixel-art/daryll.svg">
</div>

![image](https://user-images.githubusercontent.com/56125520/193402348-8409800c-6b0a-4ce2-8b7c-0704325b1dae.png)

Comment for any clarification

**Comment by Misterr-H** [comment]
hey @Maryll-castelino ,
I would like to work on it.

**Comment by llyram** [comment]
Sure @Misterr-H I'll assign this to you

**Comment by Misterr-H** [comment]
Thankyou @Maryll-castelino . I'm on it

**Comment by Misterr-H** [comment]
@Maryll-castelino 
<img width="661" alt="Screenshot 2022-10-01 at 4 20 35 PM" src="https://user-images.githubusercontent.com/55010619/193406301-d9bda598-3271-4035-93d5-7a2f0714eff7.png">

I've replaced the Avatar Icons with Dicebear Pixel Avatars using the dicebear API.
Thankyou

**Comment by llyram** [comment]
Leave a star⭐ on the repo if you like 😊
