### ISSUE TITLE
Bug: Card face overlaps on large screen sizes

### ISSUE THREAD

**Issue by JoeDravarol** [Maryll-castelino/Declare#6]
What seems wrong?
On larger screen size the card image starts to overlap/display another card face.

![image](https://user-images.githubusercontent.com/48932159/193603276-1a2ec741-6ad9-4961-a7f3-9dc287c9497b.png)

Propose changes:
- Scale the image with the card container
- Or set a size limit to prevent the card from scaling with screen sizes larger than 1920 x 1080.

**Comment by JoeDravarol** [comment]
I would like to be assign this issue if possible.

**Comment by llyram** [comment]
Thak you for volunteering @JoeDravarol I have assigned this issue to you

**Comment by llyram** [comment]
Leave a star⭐ on the repo if you like 😊
